# Generated by Django 4.0.2 on 2022-03-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del libro')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
            ],
        ),
    ]
