# Generated by Django 4.0.2 on 2022-03-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('cat01', 'Terror'), ('cat02', 'Novela'), ('cat03', 'Relatos')], default='Novela', max_length=20, verbose_name='Categoría'),
        ),
    ]
