# Generated by Django 4.0.2 on 2022-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_libro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Autor')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellido (s)')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='Alias')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fechaFallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/autores/', verbose_name='Foto del autor')),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('cat01', 'Terror'), ('cat02', 'Novela'), ('cat03', 'Relatos')], default='cat01', max_length=20, verbose_name='Categoría'),
        ),
    ]
