# Generated by Django 4.0.2 on 2022-03-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoria_editorial_alter_libro_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(to='core.Categoria', verbose_name='Seleccione la(s) categoría(s)'),
        ),
    ]
